%% Funzione per CREAZIONE DEL METAORDER SIMULATO.

function Metaorder_Finale_byISIN = MetaorderFramework(name_funds_BCC_RP, class_EUR, class_Bonds, class_Stocks_All, all_Ptf_structure, vol_asset_prices, drift_term, l_size, class_Stocks_US_NSDQ, class_Stocks_US_SP) 

        % ------------------------------------------------------------------------------------------
        % Funzione che simula i metaorder.
        % OUTPUT PRINCIPALI:
        % > Metaorder_Finale_byISIN, struttura finale che contiene i
        %   metaorder simulati per ogni titolo.
        % ------------------------------------------------------------------------------------------
        
        % Pulizia strutture in output.
        clear Metaorder_Finale_byISIN Metaorder_Provvisorio

        % % CREAZIONE DEL METAORDER.
        % Loop per ogni portafoglio.
        for k = 1 : 1 : length(name_funds_BCC_RP)

            % Estrazione struttura del j-esimo portafoglio e dei titoli che contiene.
            fund_per_titoli = readtable(string(name_funds_BCC_RP(k)), 'Sheet', string(name_funds_BCC_RP(k)), 'VariableNamingRule', 'preserve');
            titles = fund_per_titoli{1:end-1, "ISINCODE"};
            fund = readtable(string(name_funds_BCC_RP(k)), 'VariableNamingRule', 'preserve');

            % Loop per ogni titolo.
            for i = 1 : 1 : (size(fund,1)-1)

                % Cancello le variabili che definiscono le strutture di supporto per evitare sovrascrizioni.
                clear Number_of_Simulation numero_casuale_indice numero_casuale_due D array_simulato

                % Definisco un array D che contiene 50 numeri casuali uniformi da 2 a 8. La somma dei valori contenuti in questo array definisce il numero di simulazioni 
                % da fare (Number_of_Simulation). In questo modo, per ogni titolo, avrò metaorder di lunghezza differente.
                D = randi([2 8], 1000, 1);
                Number_of_Simulation = sum(D);

                % Il ciclo if di seguito è un check qualora dovesse essere necessario dividere il numero di simulazioni; 
                % trasforma infatti Number_of_Simulation in un numero pari.
                if bitget(Number_of_Simulation,1) == 1

                    Number_of_Simulation = Number_of_Simulation + 1;

                else

                    Number_of_Simulation = Number_of_Simulation;

                end


                % Due vettori di numeri casuali che utilizzerò per definire le colonne di prezzi e duration in uscita.
                Num_Casuale_Duration = randi([1 Number_of_Simulation], length(D), 1);
                Num_Casuale_Prezzi = randi([1 Number_of_Simulation], length(D), 1);

                % Pulizia delle variabili e strutture di supporto per evitare sovrascrizioni.
                clear time_out days_out mat_duration mat_price time_temporaneo start differenza Quantities

                    % Il primo If controlla se il titolo analizzato è Europeo o US.
                    %% EUROPE
                    if (ismember(fund.Val_1(i,:), class_EUR))

                        % Il secondo If controlla se il titolo è un Bond o un titolo (nel caso US, anche se il titolo è Nasdaq o SP500).
                        if (ismember(fund.TIP(i,:), class_Bonds))

                            %% 1 BOND - EU
                            [days_out, Quantities, Time_Finale, Stock_Price] = Metaorder_Simulation(name_funds_BCC_RP, ...
                                                                                                    titles, ...
                                                                                                    k, ...
                                                                                                    i, ...
                                                                                                    Number_of_Simulation, ...
                                                                                                    Num_Casuale_Duration, ...
                                                                                                    Num_Casuale_Prezzi, ...
                                                                                                    all_Ptf_structure, ...
                                                                                                    vol_asset_prices, ...
                                                                                                    drift_term, ...
                                                                                                    l_size, ...
                                                                                                    class_Stocks_All, ...
                                                                                                    class_Bonds, ...
                                                                                                    char(fund.TIP(i,:)), ...
                                                                                                    D);

                        else

                            %% 2 STOCK - EU
                            [days_out, Quantities, Time_Finale, Stock_Price] = Metaorder_Simulation(name_funds_BCC_RP, ...
                                                                                                    titles, ...
                                                                                                    k, ...
                                                                                                    i, ...
                                                                                                    Number_of_Simulation, ...
                                                                                                    Num_Casuale_Duration, ...
                                                                                                    Num_Casuale_Prezzi, ...
                                                                                                    all_Ptf_structure, ...
                                                                                                    vol_asset_prices, ...
                                                                                                    drift_term, ...
                                                                                                    l_size, ...
                                                                                                    class_Stocks_All, ...
                                                                                                    class_Bonds, ...
                                                                                                    char(fund.TIP(i,:)), ...
                                                                                                    D);                    


                        end

                    else

                        if (ismember(fund.TIP(i,:), class_Bonds))

                            %% BOND - US
                            [days_out, Quantities, Time_Finale, Stock_Price] = Metaorder_Simulation(name_funds_BCC_RP, ...
                                                                                                    titles, ...
                                                                                                    k, ...
                                                                                                    i, ...
                                                                                                    Number_of_Simulation, ...
                                                                                                    Num_Casuale_Duration, ...
                                                                                                    Num_Casuale_Prezzi, ...
                                                                                                    all_Ptf_structure, ...
                                                                                                    vol_asset_prices, ...
                                                                                                    drift_term, ...
                                                                                                    l_size, ...
                                                                                                    class_Stocks_All, ...
                                                                                                    class_Bonds, ...
                                                                                                    char(fund.TIP(i,:)), ...
                                                                                                    D);                    

                        else  

                            if (ismember(fund.Naz(i,:), class_Stocks_US_NSDQ))   

                               %% 4 STOCK - US NASDAQ
                               [days_out, Quantities, Time_Finale, Stock_Price] = Metaorder_Simulation(name_funds_BCC_RP, ...
                                                                                                       titles, ...
                                                                                                       k, ...
                                                                                                       i, ...
                                                                                                       Number_of_Simulation, ...
                                                                                                       Num_Casuale_Duration, ...
                                                                                                       Num_Casuale_Prezzi, ...
                                                                                                       all_Ptf_structure, ...
                                                                                                       vol_asset_prices, ...
                                                                                                       drift_term, ...
                                                                                                       l_size, ...
                                                                                                       class_Stocks_All, ...
                                                                                                       class_Bonds, ...
                                                                                                       char(fund.TIP(i,:)), ...
                                                                                                       D);                        


                            elseif (ismember(fund.Naz(i,:), class_Stocks_US_SP))

                                %% 5 STOCK - US Altri   
                                [days_out, Quantities, Time_Finale, Stock_Price] = Metaorder_Simulation(name_funds_BCC_RP, ...
                                                                                                        titles, ...
                                                                                                        k, ...
                                                                                                        i, ...
                                                                                                        Number_of_Simulation, ...
                                                                                                        Num_Casuale_Duration, ...
                                                                                                        Num_Casuale_Prezzi, ...
                                                                                                        all_Ptf_structure, ...
                                                                                                        vol_asset_prices, ...
                                                                                                        drift_term, ...
                                                                                                        l_size, ...
                                                                                                        class_Stocks_All, ...
                                                                                                        class_Bonds, ...
                                                                                                        char(fund.TIP(i,:)), ...
                                                                                                        D);

                            end

                        end

                    end

                    % Storing delle quantità.
                    Metaorder_Provvisorio_bySize = table(days_out, Time_Finale, Quantities, Stock_Price);
                    Metaorder_Provvisorio_bySize.Properties.VariableNames = ["Execution_Day"; "Execution_Time"; "Traded_Quantity"; "Execution_Price"];


                    % Struttura provvisora per ogni titolo.
                    Metaorder_Provvisorio.(titles{i}) = Metaorder_Provvisorio_bySize;

                    % Pulizia.
                    clear Metaorder_Provvisorio_bySize

            end

            % % STRUTTURA FINALE DEI METAORDER.
            Metaorder_Finale_byISIN.(name_funds_BCC_RP{k}) = Metaorder_Provvisorio;

            % Pulizia.
            clear Metaorder_Provvisorio
    
        end
        
end